[project]
name = "rlrn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium>=1.2.0",
    "numpy>=2.3.2",
    "torch>=2.8.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.9",
]
